// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"LookSharp/token"
)

const (
	NoState    = -1
	NumStates  = 73
	NumSymbols = 83
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: ' '
2: '!'
3: '?'
4: '"'
5: '0'
6: 'd'
7: 'o'
8: 'l'
9: 'l'
10: 'a'
11: 'b'
12: 'i'
13: 'l'
14: 'l'
15: 'l'
16: 'e'
17: 't'
18: 'i'
19: 'f'
20: 'e'
21: 'l'
22: 's'
23: 'e'
24: 'r'
25: 'e'
26: 't'
27: 'u'
28: 'r'
29: 'n'
30: 't'
31: 'r'
32: 'u'
33: 'e'
34: 'f'
35: 'a'
36: 'l'
37: 's'
38: 'e'
39: 'a'
40: 'n'
41: 'd'
42: 'o'
43: 'r'
44: '+'
45: '-'
46: '*'
47: '/'
48: '='
49: '='
50: '!'
51: '='
52: '<'
53: '='
54: '<'
55: '>'
56: '='
57: '>'
58: '$'
59: \u20ac
60: '='
61: '('
62: ')'
63: ','
64: ';'
65: '_'
66: '\t'
67: '\n'
68: '\r'
69: ' '
70: '/'
71: '/'
72: '\n'
73: '/'
74: '*'
75: '*'
76: '*'
77: '/'
78: '1'-'9'
79: 'A'-'Z'
80: 'a'-'z'
81: '0'-'9'
82: .
*/
